id: I59A99406
ocr_import_info:
  timestamp: '2023-09-28T02:50:19.433594+00:00'
  batch_id: batch-f5b7
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 03:26:09.345408+00:00
last_modified: 2023-09-28 03:26:09.345413+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG18187
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG18187
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་མངོན་པ་མཛོད་ཀྱི་མཛུབ་ཁྲིད།
  languages:
  - bo
  author: ཚུལ་ཁང་མཁན་ཟུར་ཡེ་ཤེས་ཐུབ་བསྟན།
statistics:
  ocr_word_mean_confidence_index: 0.9965444075271895
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG18234:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18234
      total_pages: 272
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18234.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9965444075271895
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
